name: حوت 54 - رادار
on:
  schedule:
    - cron: '30 8 * * 1-5'
    - cron: '30 13 * * 1-5'
    - cron: '0 20 * * 1-5'
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send
        run: curl -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage -d chat_id=13889370 -d text="👑 رادار الحوت فحص"
